version: '3'

services:
  hugo:
    # image: golang:alpine
    build: .
    volumes:
      - .:/hugo
      - setup:/hugo/setup
      - log:/hugo/log
      - ./log/hugo:/var/log/hugo:rw
    working_dir: /hugo
    command:
      - sh
      - -c
      - |
        hugo server -D --bind="0.0.0.0" --logFile="/var/log/hugo/hugo.log"
    environment:
      - GOPATH=/go

  proxy:
    image: nginx:latest
    ports:
      - 3000:3000
    volumes:
      - ./setup/nginx:/etc/nginx:ro
      - ./log/nginx:/var/log/nginx:rw
    links:
      - hugo:hugo

volumes:
  setup:
  log:
