version: '3.6'

services:
  hugo:
    build: .
    volumes:
      - ./hugo:/hugo
      - ../html:/hugo/public
    working_dir: /hugo
    ports:
      - 3000:3000
    command:
      - sh
      - -c
      - |
        echo "run hugo" && hugo server -D --bind="0.0.0.0"
