version: '3.6'

services:
  hugo:
    build: .
    volumes:
    working_dir: /hugo
    ports:
      - 3000:3000
    command:
      - sh
      - -c
      - |
        hugo server -D --bind="0.0.0.0" --logFile="/var/log/hugo/hugo.log"

volumes:
  log:
